import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthContext } from "../auth/auth-store";
import { api } from "../../api/client";
import { AppLayout } from "../../layouts/app-layout";
import { InvoiceDetails, InvoiceGenerator, InvoicesPage } from "./invoices-page";
vi.mock("../../api/client", () => ({ api: { get: vi.fn(), post: vi.fn() } }));
const invoice = { id: "inv-1", business_id: "b", order_id: "order-1", invoice_number: "INV-000001", status: "issued", issued_at: "2026-01-01T10:00:00Z", order_number: "SO-100", customer_name: "Ada", customer_email: "ada@example.com", customer_address: "1 Main Street", customer_tax_id: "GST-1", subtotal: "100.00", tax_total: "18.00", grand_total: "118.00", paid_amount: "50.00", remaining_balance: "68.00", payment_state: "partially_paid", created_at: "2026-01-01T10:00:00Z", updated_at: "2026-01-01T10:00:00Z", items: [{ id: "line-1", product_name: "Widget", product_sku: "SKU-1", quantity: "2.000", unit_price: "50.00", tax_rate: "18.00", line_subtotal: "100.00", line_tax: "18.00", line_total: "118.00" }] };
function Wrap({ children, grants = ["invoices.view", "invoices.create"], initial = "/invoices/inv-1" }: { children: React.ReactNode; grants?: string[]; initial?: string }) { const query = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return <MemoryRouter initialEntries={[initial]}><QueryClientProvider client={query}><AuthContext.Provider value={{ session: { user: { id: "u", email: "a@example.com", full_name: "A", business_id: "b", roles: [], permissions: grants }, business: { id: "b", name: "Alpha", slug: "alpha" }, access_token: "x", refresh_token: "y", token_type: "bearer" }, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.get).mockImplementation(async (url: string) => ({ data: url === "/invoices" ? { items: [invoice], total: 1, page: 1, page_size: 20 } : url === "/orders" ? { items: [{ id: "order-1", order_number: "SO-100", status: "confirmed", grand_total: "118.00" }] } : invoice })); vi.mocked(api.post).mockResolvedValue({ data: invoice }); }); afterEach(cleanup);
function mockBrowserDownload(): { createObjectURL: ReturnType<typeof vi.fn>; revokeObjectURL: ReturnType<typeof vi.fn>; downloads: string[]; anchors: HTMLAnchorElement[]; restore: () => void } {
 const originalCreate = Object.getOwnPropertyDescriptor(URL, "createObjectURL"); const originalRevoke = Object.getOwnPropertyDescriptor(URL, "revokeObjectURL"); const createObjectURL = vi.fn(() => "blob:invoice"); const revokeObjectURL = vi.fn(); const downloads: string[] = []; const anchors: HTMLAnchorElement[] = [];
 Object.defineProperty(URL, "createObjectURL", { configurable: true, value: createObjectURL }); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: revokeObjectURL }); const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(function (this: HTMLAnchorElement) { downloads.push(this.download); anchors.push(this); });
 return { createObjectURL, revokeObjectURL, downloads, anchors, restore: () => { click.mockRestore(); if (originalCreate) Object.defineProperty(URL, "createObjectURL", originalCreate); else Reflect.deleteProperty(URL, "createObjectURL"); if (originalRevoke) Object.defineProperty(URL, "revokeObjectURL", originalRevoke); else Reflect.deleteProperty(URL, "revokeObjectURL"); } };
}
describe("invoices UX", () => {
 it("renders the server invoice list and permission-gated generation", async () => { render(<Wrap grants={["invoices.view"]}><InvoicesPage /></Wrap>); expect(await screen.findByText("INV-000001")).toBeTruthy(); expect(screen.getByText("₹118.00")).toBeTruthy(); expect(screen.getByText("partially paid")).toBeTruthy(); expect(screen.queryByText("Generate invoice")).toBeNull(); });
 it("renders loading, empty, and error states", async () => { vi.mocked(api.get).mockImplementation(() => new Promise(() => {})); const loading = render(<Wrap><InvoicesPage /></Wrap>); expect(screen.getByRole("status").textContent).toContain("Loading invoices…"); loading.unmount(); vi.mocked(api.get).mockResolvedValue({ data: { items: [], total: 0, page: 1, page_size: 20 } }); const empty = render(<Wrap><InvoicesPage /></Wrap>); expect(await screen.findByText("No invoices match this search.")).toBeTruthy(); empty.unmount(); vi.mocked(api.get).mockRejectedValue(new Error("Network")); render(<Wrap><InvoicesPage /></Wrap>); expect(await screen.findByText("Unable to complete the request. Please try again.")).toBeTruthy(); });
 it("validates generation and submits only the backend order_id payload", async () => { render(<Wrap initial="/invoices/new"><Routes><Route path="/invoices/new" element={<InvoiceGenerator />} /><Route path="/invoices/:invoiceId" element={<p>Detail</p>} /></Routes></Wrap>); await screen.findByRole("combobox", { name: "Confirmed order" }); fireEvent.submit(screen.getByRole("button", { name: "Generate invoice" }).closest("form")!); expect(await screen.findByText("Choose a confirmed order.")).toBeTruthy(); fireEvent.change(screen.getByRole("combobox"), { target: { value: "order-1" } }); fireEvent.click(screen.getByRole("button", { name: "Generate invoice" })); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/invoices", { order_id: "order-1" })); expect(await screen.findByText("Detail")).toBeTruthy(); });
 it("renders immutable server snapshots and totals", async () => { render(<Wrap><Routes><Route path="/invoices/:invoiceId" element={<InvoiceDetails />} /></Routes></Wrap>); expect(await screen.findByText("Widget")).toBeTruthy(); expect(screen.getByText("Grand total: ₹118.00")).toBeTruthy(); expect(screen.getByText("₹68.00")).toBeTruthy(); expect(screen.queryByRole("button", { name: /edit|delete/i })).toBeNull(); });
 it("downloads the invoice PDF once with a deterministic filename and defensive cleanup", async () => {
  const browserDownload = mockBrowserDownload(); const pdf = new Blob(["pdf"], { type: "application/pdf" }); let resolvePdf: ((value: { data: Blob }) => void) | undefined; const pendingPdf = new Promise<{ data: Blob }>(resolve => { resolvePdf = resolve; }); vi.mocked(api.get).mockImplementation(async url => url.endsWith("/pdf") ? pendingPdf : { data: invoice });
  try { render(<Wrap><Routes><Route path="/invoices/:invoiceId" element={<InvoiceDetails />} /></Routes></Wrap>); const button = await screen.findByRole("button", { name: "Download PDF" }); fireEvent.click(button); const pendingButton = await screen.findByRole("button", { name: "Downloading…" }); expect(pendingButton.hasAttribute("disabled")).toBe(true); fireEvent.click(pendingButton); expect(vi.mocked(api.get).mock.calls.filter(([url]) => url === "/invoices/inv-1/pdf")).toHaveLength(1); resolvePdf?.({ data: pdf }); await screen.findByRole("button", { name: "Download PDF" }); expect(api.get).toHaveBeenCalledWith("/invoices/inv-1/pdf", { responseType: "blob" }); expect(browserDownload.createObjectURL).toHaveBeenCalledWith(pdf); expect(browserDownload.downloads).toEqual(["invoice-INV-000001.pdf"]); expect(browserDownload.anchors[0]?.isConnected).toBe(false); expect(document.querySelector('a[download="invoice-INV-000001.pdf"]')).toBeNull(); expect(browserDownload.revokeObjectURL).toHaveBeenCalledWith("blob:invoice"); } finally { browserDownload.restore(); }
 });
 it("shows a controlled PDF download error without replacing invoice details", async () => {
  vi.mocked(api.get).mockImplementation(async url => { if (url.endsWith("/pdf")) throw new Error("Network"); return { data: invoice }; }); render(<Wrap><Routes><Route path="/invoices/:invoiceId" element={<InvoiceDetails />} /></Routes></Wrap>); fireEvent.click(await screen.findByRole("button", { name: "Download PDF" })); expect(await screen.findByText("Unable to complete the request. Please try again.")).toBeTruthy(); expect(screen.getByText("Widget")).toBeTruthy(); expect(screen.getByText("Grand total: ₹118.00")).toBeTruthy(); expect(screen.getByRole("button", { name: "Download PDF" }).hasAttribute("disabled")).toBe(false);
 });
 it("gates invoice navigation by view permission", () => { render(<Wrap grants={["invoices.view"]} initial="/"><Routes><Route path="/" element={<AppLayout />}><Route index element={<p>Home</p>} /></Route></Routes></Wrap>); expect(screen.getByText("Invoices")).toBeTruthy(); cleanup(); render(<Wrap grants={[]} initial="/"><Routes><Route path="/" element={<AppLayout />}><Route index element={<p>Home</p>} /></Route></Routes></Wrap>); expect(screen.queryByText("Invoices")).toBeNull(); });
});
