import { useRef, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../api/client";
import { Button, Card, Table } from "../../components/ui";
import { Can } from "../team/permissions";
import { Feedback } from "../team/shared";
import { errorMessage } from "../team/errors";

type PaymentState = "unpaid" | "partially_paid" | "paid";
type InvoiceItem = { id: string; product_name: string; product_sku: string; quantity: string; unit_price: string; tax_rate: string; line_subtotal: string; line_tax: string; line_total: string };
type Invoice = { id: string; business_id: string; order_id: string; invoice_number: string; status: "issued"; issued_at: string; order_number: string; customer_name: string; customer_email: string | null; customer_address: string | null; customer_tax_id: string | null; subtotal: string; tax_total: string; grand_total: string; paid_amount: string; remaining_balance: string; payment_state: PaymentState; created_at: string; updated_at: string; items: InvoiceItem[] };
type InvoicePage = { items: Invoice[]; total: number; page: number; page_size: number };
type Order = { id: string; order_number: string; status: "draft" | "confirmed" | "cancelled"; grand_total: string };
const invoiceKey = ["invoices"] as const;
const detailKey = (id: string) => ["invoice", id] as const;
const money = (value: string) => `₹${value}`;
const stateClasses: Record<PaymentState, string> = { unpaid: "bg-gray-100 text-gray-700", partially_paid: "bg-blue-50 text-blue-700", paid: "bg-green-50 text-green-700" };
export function InvoicePaymentStateBadge({ state }: { state: PaymentState }): JSX.Element { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${stateClasses[state]}`}>{state.replace("_", " ")}</span>; }
function useConfirmedOrders() { return useQuery({ queryKey: ["orders", "invoice-options"], queryFn: async () => (await api.get<{ items: Order[] }>("/orders", { params: { status: "confirmed", page_size: 100 } })).data.items }); }

function DownloadInvoicePdfButton({ invoiceId, invoiceNumber }: { invoiceId: string; invoiceNumber: string }): JSX.Element {
 const [isDownloading, setIsDownloading] = useState(false); const [downloadError, setDownloadError] = useState(""); const downloadInProgress = useRef(false);
 const download = async (): Promise<void> => { if (downloadInProgress.current) return; downloadInProgress.current = true; setIsDownloading(true); setDownloadError(""); let objectUrl: string | undefined; let anchor: HTMLAnchorElement | undefined; try { const response = await api.get<Blob>(`/invoices/${invoiceId}/pdf`, { responseType: "blob" }); objectUrl = URL.createObjectURL(response.data); anchor = document.createElement("a"); anchor.href = objectUrl; const safeNumber = invoiceNumber.replace(/[^A-Za-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "invoice"; anchor.download = `invoice-${safeNumber}.pdf`; anchor.style.display = "none"; document.body.appendChild(anchor); anchor.click(); } catch (error) { setDownloadError(errorMessage(error)); } finally { anchor?.remove(); if (objectUrl) URL.revokeObjectURL(objectUrl); downloadInProgress.current = false; setIsDownloading(false); } };
 return <div className="space-y-2"><Button type="button" disabled={isDownloading} onClick={() => void download()}>{isDownloading ? "Downloading…" : "Download PDF"}</Button><Feedback error={downloadError || undefined} /></div>;
}

export function InvoicesPage(): JSX.Element {
 const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const rows = useQuery({ queryKey: [...invoiceKey, search, page], queryFn: async () => (await api.get<InvoicePage>("/invoices", { params: { search: search || undefined, page, page_size: 20 } })).data });
 return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Invoices</h1><p className="mt-1 text-sm text-gray-500">Issued order snapshots and their payment status.</p></div><Can permission="invoices.create"><Link to="/invoices/new"><Button>Generate invoice</Button></Link></Can></div><Card><div className="mb-5 max-w-sm"><label className="label">Search invoices<input className="field" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Invoice, order, or customer" /></label></div>{rows.isPending ? <p role="status">Loading invoices…</p> : rows.isError ? <><Feedback error={errorMessage(rows.error)} /><button onClick={() => void rows.refetch()}>Retry</button></> : <><Table columns={["Invoice", "Order", "Customer", "Issued", "Status", "Payment", "Total", "Actions"]}>{rows.data.items.map(invoice => <tr key={invoice.id}><td className="px-4 py-4"><Link className="font-medium text-blue-700" to={`/invoices/${invoice.id}`}>{invoice.invoice_number}</Link></td><td className="px-4 py-4">{invoice.order_number}</td><td className="px-4 py-4">{invoice.customer_name}</td><td className="px-4 py-4 text-xs text-gray-500">{new Date(invoice.issued_at).toLocaleDateString()}</td><td className="px-4 py-4"><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700">{invoice.status}</span></td><td className="px-4 py-4"><InvoicePaymentStateBadge state={invoice.payment_state} /></td><td className="px-4 py-4">{money(invoice.grand_total)}</td><td className="px-4 py-4"><Link className="text-sm font-medium text-blue-700" to={`/invoices/${invoice.id}`}>View</Link></td></tr>)}</Table>{!rows.data.items.length && <p className="py-10 text-center text-sm text-gray-500">No invoices match this search.</p>}<div className="mt-5 flex justify-between text-sm"><span>{rows.data.total} invoices · Page {page}</span><div className="flex gap-3"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button disabled={page * rows.data.page_size >= rows.data.total} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</Card></div>;
}

export function InvoiceGenerator(): JSX.Element {
 const navigate = useNavigate(); const cache = useQueryClient(); const orders = useConfirmedOrders(); const [orderId, setOrderId] = useState(""); const [validation, setValidation] = useState(""); const create = useMutation({ mutationFn: async () => (await api.post<Invoice>("/invoices", { order_id: orderId })).data, onSuccess: async invoice => { await cache.invalidateQueries({ queryKey: invoiceKey }); navigate(`/invoices/${invoice.id}`); } }); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!orderId) { setValidation("Choose a confirmed order."); return; } setValidation(""); create.mutate(); };
 return <div className="space-y-5"><div><Link className="text-sm font-medium text-blue-700" to="/invoices">← Invoices</Link><h1 className="mt-3 text-2xl font-semibold">Generate invoice</h1><p className="mt-1 text-sm text-gray-500">The issued invoice is a read-only snapshot created by the server.</p></div><Card><form noValidate onSubmit={submit} className="space-y-4"><label className="label">Confirmed order<select className="field" value={orderId} onChange={event => setOrderId(event.target.value)}><option value="">Select order</option>{(orders.data ?? []).map(order => <option key={order.id} value={order.id}>{order.order_number} · {money(order.grand_total)}</option>)}</select></label><Feedback error={validation || (create.isError ? errorMessage(create.error) : undefined)} /><div className="flex gap-3"><Button disabled={create.isPending}>{create.isPending ? "Generating…" : "Generate invoice"}</Button><Link to="/invoices">Cancel</Link></div></form></Card></div>;
}

export function InvoiceDetails(): JSX.Element {
 const { invoiceId = "" } = useParams(); const invoice = useQuery({ queryKey: detailKey(invoiceId), queryFn: async () => (await api.get<Invoice>(`/invoices/${invoiceId}`)).data }); if (invoice.isPending) return <p role="status">Loading invoice…</p>; if (invoice.isError) return <Feedback error={errorMessage(invoice.error)} />; const value = invoice.data;
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="text-sm font-medium text-blue-700" to="/invoices">← Invoices</Link><h1 className="mt-3 text-2xl font-semibold">{value.invoice_number}</h1><p className="mt-1 text-sm text-gray-500">Issued {new Date(value.issued_at).toLocaleString()} · Order {value.order_number}</p></div><div className="flex flex-wrap items-start gap-2"><DownloadInvoicePdfButton invoiceId={value.id} invoiceNumber={value.invoice_number} /><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700">{value.status}</span><InvoicePaymentStateBadge state={value.payment_state} /></div></div><div className="grid gap-5 md:grid-cols-2"><Card><h2 className="mb-3 font-semibold">Customer snapshot</h2><p className="font-medium">{value.customer_name}</p><p className="mt-2 text-sm text-gray-600">{value.customer_email ?? "No email recorded"}</p><p className="mt-2 whitespace-pre-wrap text-sm text-gray-600">{value.customer_address ?? "No billing address recorded"}</p>{value.customer_tax_id && <p className="mt-2 text-sm text-gray-600">Tax ID: {value.customer_tax_id}</p>}</Card><Card><h2 className="mb-3 font-semibold">Payment summary</h2><p className="text-sm text-gray-500">Paid amount</p><p className="text-xl font-semibold">{money(value.paid_amount)}</p><p className="mt-2 text-sm text-gray-600">Remaining balance: <span className="font-medium text-gray-900">{money(value.remaining_balance)}</span></p></Card></div><Card><h2 className="mb-4 font-semibold">Invoice items</h2><Table columns={["Product", "Quantity", "Unit price", "Tax rate", "Subtotal", "Tax", "Total"]}>{value.items.map(item => <tr key={item.id}><td className="px-4 py-4">{item.product_name}<div className="text-xs text-gray-500">{item.product_sku}</div></td><td className="px-4 py-4">{item.quantity}</td><td className="px-4 py-4">{money(item.unit_price)}</td><td className="px-4 py-4">{item.tax_rate}%</td><td className="px-4 py-4">{money(item.line_subtotal)}</td><td className="px-4 py-4">{money(item.line_tax)}</td><td className="px-4 py-4">{money(item.line_total)}</td></tr>)}</Table><div className="mt-5 space-y-1 text-right text-sm"><p>Subtotal: {money(value.subtotal)}</p><p>Tax: {money(value.tax_total)}</p><p className="text-lg font-semibold">Grand total: {money(value.grand_total)}</p></div></Card></div>;
}
