import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthContext } from "../auth/auth-store";
import { api } from "../../api/client";
import { OrderDetails, OrdersPage } from "./orders-page";

vi.mock("../../api/client", () => ({ api: { get: vi.fn(), post: vi.fn(), request: vi.fn() } }));
const order={id:"o1",customer_id:"c1",order_number:"SO-1",status:"draft",order_date:"2026-01-01T00:00:00Z",notes:null,subtotal:"10.00",tax_total:"1.00",grand_total:"11.00",items:[{id:"i1",product_id:"p1",product_name:"Widget",product_sku:"W1",quantity:"1.000",unit_price:"10.00",line_tax:"1.00",line_total:"11.00"}]};
function Wrap({children,grants=["orders.view","orders.create","orders.update","orders.confirm","orders.cancel"]}:{children:React.ReactNode;grants?:string[]}){const q=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return <MemoryRouter initialEntries={["/orders/o1"]}><QueryClientProvider client={q}><AuthContext.Provider value={{session:null,isLoading:false,can:p=>grants.includes(p),login:async()=>{},register:async()=>{},logout:async()=>{}}}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>}
beforeEach(()=>{vi.clearAllMocks();HTMLDialogElement.prototype.showModal=function(){this.open=true};HTMLDialogElement.prototype.close=function(){this.open=false};vi.mocked(api.get).mockImplementation(async(url:string)=>({data:url==="/orders"?{items:[order],total:1,page:1,page_size:20}:url==="/customers"?{items:[{id:"c1",display_name:"Ava"}]}:order}));vi.mocked(api.post).mockResolvedValue({data:{...order,status:"confirmed"}})});afterEach(cleanup);
describe("orders UX",()=>{it("renders list, status, and permission-gated create",async()=>{render(<Wrap grants={["orders.view"]}><OrdersPage/></Wrap>);expect(await screen.findByText("SO-1")).toBeTruthy();expect(screen.getByText("draft")).toBeTruthy();expect(screen.queryByText("Create order")).toBeNull()});it("renders empty and loading states",async()=>{vi.mocked(api.get).mockResolvedValueOnce({data:{items:[],total:0,page:1,page_size:20}});render(<Wrap><OrdersPage/></Wrap>);expect(await screen.findByText("No orders match these filters.")).toBeTruthy()});it("renders details and confirms through the API",async()=>{render(<Wrap><Routes><Route path="/orders/:orderId" element={<OrderDetails/>}/></Routes></Wrap>);expect(await screen.findByText("Widget")).toBeTruthy();fireEvent.click(screen.getByText("Confirm order"));fireEvent.click(screen.getByText("Confirm"));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/orders/o1/confirm"))})});
