import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AxiosError, type AxiosResponse } from "axios";
import type { PropsWithChildren } from "react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthContext } from "../auth/auth-store";
import { api } from "../../api/client";
import { ProductDetails, ProductEditor, ProductsPage, type Product } from "./products-page";

vi.mock("../../api/client", () => ({ api: { get: vi.fn(), request: vi.fn(), post: vi.fn(), delete: vi.fn() } }));
const product: Product = { id: "p1", name: "Widget", sku: "WID-001", barcode: null, description: null, category: "Tools", brand: null, unit_of_measure: "piece", selling_price: "19.99", cost_price: "10.00", tax_rate: null, track_inventory: true, reorder_level: null, notes: null, status: "active", suppliers: [], created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" };
function Wrapper({ children, grants = ["products.view", "products.create", "products.update", "products.deactivate", "products.delete"] }: PropsWithChildren<{ grants?: string[] }>): JSX.Element { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return <MemoryRouter><QueryClientProvider client={client}><AuthContext.Provider value={{ session: null, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
const inventory = { id: "i1", product_id: "p1", product_name: "Widget", sku: "WID-001", unit_of_measure: "piece", quantity_on_hand: "4.000", reorder_level: null, stock_status: "in_stock", updated_at: "2026-01-01T00:00:00Z" } as const;
const httpError = (status?: number) => new AxiosError(status ? `HTTP ${status}` : "Network error", status ? AxiosError.ERR_BAD_REQUEST : AxiosError.ERR_NETWORK, undefined, undefined, status ? { status, statusText: "Error", headers: {}, config: { headers: {} }, data: { detail: `Inventory lookup failed (${status}).` } } as AxiosResponse : undefined);
type InventoryLookup = { status: number; data?: typeof inventory } | Error;
function renderDetails({ selected = product, grants = ["products.view", "inventory.view", "inventory.adjust"], inventoryResult = { status: 404 } }: { selected?: Product; grants?: string[]; inventoryResult?: InventoryLookup } = {}) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); const invalidate = vi.spyOn(client, "invalidateQueries");
  vi.mocked(api.get).mockImplementation(async url => { if (url === "/products/p1") return { data: selected }; if (url === "/suppliers") return { data: { items: [] } }; if (url === "/inventory/p1") { if (inventoryResult instanceof Error) throw inventoryResult; return { status: inventoryResult.status, data: inventoryResult.data ?? { detail: "Inventory not found." } }; } return { data: { items: [], total: 0, page: 1, page_size: 20 } }; });
  render(<MemoryRouter initialEntries={["/products/p1"]}><QueryClientProvider client={client}><AuthContext.Provider value={{ session: null, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}><Routes><Route path="/products/:productId" element={<ProductDetails />} /><Route path="/inventory/:productId" element={<p>Inventory destination</p>} /></Routes></AuthContext.Provider></QueryClientProvider></MemoryRouter>);
  return { invalidate };
}
beforeEach(() => { vi.clearAllMocks(); HTMLDialogElement.prototype.showModal = function () { this.open = true; }; HTMLDialogElement.prototype.close = function () { this.open = false; }; vi.mocked(api.get).mockResolvedValue({ data: { items: [product], total: 1, page: 1, page_size: 20 } }); vi.mocked(api.request).mockResolvedValue({ data: product }); vi.mocked(api.post).mockResolvedValue({ data: inventory }); }); afterEach(cleanup);
describe("product management UX", () => {
  it("renders products and hides restricted actions", async () => { render(<Wrapper grants={["products.view"]}><ProductsPage /></Wrapper>); expect(await screen.findByText("Widget")).toBeTruthy(); expect(screen.queryByText("Add product")).toBeNull(); expect(screen.queryByText("Edit")).toBeNull(); });
  it("renders empty and error states", async () => { vi.mocked(api.get).mockResolvedValueOnce({ data: { items: [], total: 0, page: 1, page_size: 20 } }); render(<Wrapper><ProductsPage /></Wrapper>); expect(await screen.findByText("No products match these filters.")).toBeTruthy(); cleanup(); vi.mocked(api.get).mockRejectedValueOnce(new Error("offline")); render(<Wrapper><ProductsPage /></Wrapper>); expect(await screen.findByText("Unable to complete the request. Please try again.")).toBeTruthy(); });
  it("validates prices and submits product data", async () => { render(<Wrapper><ProductEditor /></Wrapper>); fireEvent.click(screen.getByText("Save product")); expect(await screen.findByText("Enter at least two characters.")).toBeTruthy(); fireEvent.change(document.querySelector('input[name="name"]')!, { target: { value: "Nova Kit" } }); fireEvent.change(document.querySelector('input[name="sku"]')!, { target: { value: "NOVA-1" } }); fireEvent.change(document.querySelector('input[name="selling_price"]')!, { target: { value: "25.50" } }); fireEvent.click(screen.getByText("Save product")); await waitFor(() => expect(api.request).toHaveBeenCalledWith(expect.objectContaining({ method: "post", url: "/products", data: expect.objectContaining({ name: "Nova Kit", sku: "NOVA-1", selling_price: "25.50" }) }))); });
  it("initializes missing inventory with the reused opening-balance dialog and navigates", async () => { const { invalidate } = renderDetails(); expect(await screen.findByText("Initialize inventory")).toBeTruthy(); fireEvent.click(screen.getByText("Initialize inventory")); expect(screen.getByText("Opening balance")).toBeTruthy(); expect(screen.queryByLabelText("Operation")).toBeNull(); expect(screen.getByText(/Current quantity:/).textContent).toContain("0 piece"); fireEvent.click(screen.getByText("Save adjustment")); expect(await screen.findByText("Enter a quantity greater than zero.")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Quantity"), { target: { value: "8" } }); fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "x" } }); fireEvent.click(screen.getByText("Save adjustment")); expect(await screen.findByText("Enter a reason with at least two characters.")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Initial stock" } }); fireEvent.change(screen.getByLabelText("Notes (optional)"), { target: { value: "Opening count" } }); fireEvent.click(screen.getByText("Save adjustment")); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/inventory/p1/adjust", { operation: "opening_balance", quantity: "8", reason: "Initial stock", notes: "Opening count" })); expect(await screen.findByText("Inventory destination")).toBeTruthy(); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["inventory"] }); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["inventory", "p1"] }); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["inventory", "p1", "movements"] }); });
  it("does not initialize when inventory already exists", async () => { renderDetails({ inventoryResult: { status: 200, data: inventory } }); expect(await screen.findByText("View inventory")).toBeTruthy(); expect(screen.queryByText("Initialize inventory")).toBeNull(); });
  it.each([{ label: "untracked", selected: { ...product, track_inventory: false } }, { label: "inactive", selected: { ...product, status: "inactive" as const } }])("does not check or initialize an $label product", async ({ selected }) => { renderDetails({ selected }); expect(await screen.findByText("Widget")).toBeTruthy(); await waitFor(() => expect(vi.mocked(api.get).mock.calls.some(([url]) => url === "/inventory/p1")).toBe(false)); expect(screen.queryByText("Initialize inventory")).toBeNull(); });
  it("hides initialization without inventory.adjust", async () => { renderDetails({ grants: ["products.view", "inventory.view"] }); expect(await screen.findByText("Inventory configuration")).toBeTruthy(); await waitFor(() => expect(api.get).toHaveBeenCalledWith("/inventory/p1", expect.objectContaining({ validateStatus: expect.any(Function) }))); expect(screen.queryByText("Initialize inventory")).toBeNull(); });
  it.each([403, 500, undefined])("does not treat a %s inventory lookup failure as missing", async status => { renderDetails({ inventoryResult: httpError(status) }); expect(await screen.findByText(status ? `Inventory lookup failed (${status}).` : "Unable to reach BusinessOS. Please try again.")).toBeTruthy(); expect(screen.queryByText("Initialize inventory")).toBeNull(); });
  it("keeps initialization open and does not navigate after an API failure", async () => { vi.mocked(api.post).mockRejectedValueOnce(httpError(500)); renderDetails(); fireEvent.click(await screen.findByText("Initialize inventory")); fireEvent.change(screen.getByLabelText("Quantity"), { target: { value: "8" } }); fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Initial stock" } }); fireEvent.click(screen.getByText("Save adjustment")); expect(await screen.findByText("Inventory lookup failed (500).")).toBeTruthy(); expect(screen.getAllByRole("dialog")).toHaveLength(2); expect(screen.queryByText("Inventory destination")).toBeNull(); });
});
