import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../api/client";
import { Button, Card, Input, Table } from "../../components/ui";
import { Can } from "../team/permissions";
import { Dialog, Feedback } from "../team/shared";
import { errorMessage } from "../team/errors";
import { CustomerForm } from "./customer-form";
import type { Customer, CustomerPage, CustomerWrite } from "./types";

const queryKey = ["customers"];
const detailKey = (id: string) => ["customer", id];

export function CustomersPage(): JSX.Element {
  const cache = useQueryClient(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [page, setPage] = useState(1); const [confirm, setConfirm] = useState<{ customer: Customer; action: "activate" | "deactivate" | "delete" } | null>(null); const [success, setSuccess] = useState("");
  const customers = useQuery({ queryKey: [...queryKey, search, status, type, page], queryFn: async () => (await api.get<CustomerPage>("/customers", { params: { search, status: status || undefined, customer_type: type || undefined, page, page_size: 20 } })).data });
  const action = useMutation({ mutationFn: async ({ customer, kind }: { customer: Customer; kind: "activate" | "deactivate" | "delete" }) => api.request({ method: kind === "delete" ? "delete" : "post", url: `/customers/${customer.id}${kind === "delete" ? "" : `/${kind}`}` }), onSuccess: async () => { await cache.invalidateQueries({ queryKey }); setConfirm(null); setSuccess("Customer updated successfully."); } });
  const updateFilter = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setter(event.target.value); setPage(1); };
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Customers</h1><p className="mt-1 text-sm text-gray-500">Manage the customers your business serves.</p></div><Can permission="customers.create"><Link to="/customers/new"><Button>Add customer</Button></Link></Can></div><Feedback success={success} error={!confirm && action.isError ? errorMessage(action.error) : undefined} />
    <Card><div className="mb-5 grid gap-3 sm:grid-cols-3"><Input label="Search customers" type="search" value={search} placeholder="Name, company, email or phone" onChange={updateFilter(setSearch)} /><label className="label">Status<select className="field" value={status} onChange={updateFilter(setStatus)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="label">Customer type<select className="field" value={type} onChange={updateFilter(setType)}><option value="">All types</option><option value="individual">Individual</option><option value="business">Business</option></select></label></div>
      {customers.isPending ? <p role="status">Loading customers…</p> : customers.isError ? <><Feedback error={errorMessage(customers.error)} /><button onClick={() => void customers.refetch()}>Retry</button></> : <><Table columns={["Customer", "Company", "Contact", "Type", "Status", "Created", "Actions"]}>{customers.data.items.map(customer => <tr key={customer.id}><td className="px-4 py-4"><Link className="font-medium text-blue-700" to={`/customers/${customer.id}`}>{customer.display_name}</Link></td><td className="px-4 py-4">{customer.company_name || "—"}</td><td className="px-4 py-4"><div>{customer.email || "—"}</div><div className="text-xs text-gray-500">{customer.phone || ""}</div></td><td className="px-4 py-4 capitalize">{customer.customer_type}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs ${customer.status === "active" ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-500"}`}>{customer.status}</span></td><td className="px-4 py-4">{new Date(customer.created_at).toLocaleDateString()}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-3 text-xs font-medium text-blue-700"><Link to={`/customers/${customer.id}`}>View</Link><Can permission="customers.update"><Link to={`/customers/${customer.id}/edit`}>Edit</Link></Can><Can permission="customers.deactivate"><button disabled={action.isPending} onClick={() => setConfirm({ customer, action: customer.status === "active" ? "deactivate" : "activate" })}>{customer.status === "active" ? "Deactivate" : "Activate"}</button></Can><Can permission="customers.delete"><button className="text-red-600" disabled={action.isPending} onClick={() => setConfirm({ customer, action: "delete" })}>Delete</button></Can></div></td></tr>)}</Table>{customers.data.items.length === 0 && <p className="py-10 text-center text-sm text-gray-500">No customers match these filters.</p>}<div className="mt-5 flex items-center justify-between text-sm"><span>{customers.data.total} customers · Page {page}</span><div className="flex gap-3"><button disabled={page === 1} className="disabled:opacity-40" onClick={() => setPage(page - 1)}>Previous</button><button disabled={page * 20 >= customers.data.total} className="disabled:opacity-40" onClick={() => setPage(page + 1)}>Next</button></div></div></>}</Card>
    {confirm && <Dialog title={`${confirm.action[0].toUpperCase()}${confirm.action.slice(1)} customer`} close={() => { if (!action.isPending) setConfirm(null); }}><p className="mb-4 text-sm">Confirm {confirm.action} for {confirm.customer.display_name}? {confirm.action === "delete" ? "Historical references will be retained." : ""}</p><Feedback error={action.isError ? errorMessage(action.error) : undefined} /><Button disabled={action.isPending} onClick={() => action.mutate({ customer: confirm.customer, kind: confirm.action })}>{action.isPending ? "Updating…" : "Confirm"}</Button></Dialog>}</div>;
}

export function CustomerEditorPage(): JSX.Element {
  const { customerId } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const editing = Boolean(customerId);
  const customer = useQuery({ queryKey: detailKey(customerId ?? ""), enabled: editing, queryFn: async () => (await api.get<Customer>(`/customers/${customerId}`)).data });
  const mutation = useMutation({ mutationFn: async (data: CustomerWrite) => api.request({ method: editing ? "patch" : "post", url: editing ? `/customers/${customerId}` : "/customers", data }), onSuccess: async ({ data }) => { await cache.invalidateQueries({ queryKey }); await cache.invalidateQueries({ queryKey: detailKey(data.id) }); navigate(`/customers/${data.id}`); } });
  if (editing && customer.isPending) return <p role="status">Loading customer…</p>;
  if (editing && customer.isError) return <Feedback error={errorMessage(customer.error)} />;
  return <div className="space-y-6"><div><Link className="text-sm font-medium text-blue-700" to={editing ? `/customers/${customerId}` : "/customers"}>← Back</Link><h1 className="mt-3 text-2xl font-semibold">{editing ? "Edit customer" : "Add customer"}</h1><p className="mt-1 text-sm text-gray-500">Keep customer information accurate for future business activity.</p></div><CustomerForm customer={customer.data} saving={mutation.isPending} submit={data => mutation.mutate(data)} cancel={() => navigate(editing ? `/customers/${customerId}` : "/customers")} /><Feedback error={mutation.isError ? errorMessage(mutation.error) : undefined} /></div>;
}

export function CustomerDetailsPage(): JSX.Element {
  const { customerId = "" } = useParams(); const customer = useQuery({ queryKey: detailKey(customerId), queryFn: async () => (await api.get<Customer>(`/customers/${customerId}`)).data });
  if (customer.isPending) return <p role="status">Loading customer…</p>; if (customer.isError) return <Feedback error={errorMessage(customer.error)} />; const item = customer.data;
  const line = (...values: Array<string | null>) => values.filter(Boolean).join(", ") || "Not provided";
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="text-sm font-medium text-blue-700" to="/customers">← Customers</Link><h1 className="mt-3 text-2xl font-semibold">{item.display_name}</h1><p className="mt-1 text-sm text-gray-500">{item.customer_type === "business" ? item.company_name || "Business customer" : "Individual customer"}</p></div><div className="flex flex-wrap gap-3"><Can permission="reports.view"><Link to={`/customers/${item.id}/statement`}><Button>View statement</Button></Link></Can><Can permission="customers.update"><Link to={`/customers/${item.id}/edit`}><Button>Edit customer</Button></Link></Can></div></div><div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="mb-3 font-semibold">Customer overview</h2><dl className="space-y-3 text-sm"><div><dt className="text-gray-500">Status</dt><dd className="capitalize">{item.status}</dd></div><div><dt className="text-gray-500">Type</dt><dd className="capitalize">{item.customer_type}</dd></div><div><dt className="text-gray-500">Company</dt><dd>{item.company_name || "Not provided"}</dd></div></dl></Card><Card><h2 className="mb-3 font-semibold">Contact information</h2><dl className="space-y-3 text-sm"><div><dt className="text-gray-500">Email</dt><dd>{item.email || "Not provided"}</dd></div><div><dt className="text-gray-500">Phone</dt><dd>{line(item.phone, item.alternate_phone)}</dd></div></dl></Card><Card><h2 className="mb-3 font-semibold">Address</h2><p className="text-sm">{line(item.address_line_1, item.address_line_2)}<br />{line(item.city, item.state, item.postal_code)}<br />{item.country || "Not provided"}</p></Card><Card><h2 className="mb-3 font-semibold">Business details</h2><dl className="space-y-3 text-sm"><div><dt className="text-gray-500">Tax / GST / VAT ID</dt><dd>{item.tax_id || "Not provided"}</dd></div><div><dt className="text-gray-500">Notes</dt><dd className="whitespace-pre-wrap">{item.notes || "No notes"}</dd></div></dl></Card></div><p className="text-sm text-gray-500">Created {new Date(item.created_at).toLocaleString()} · Updated {new Date(item.updated_at).toLocaleString()}</p></div>;
}
