"""Inventory ledger.
Revision ID: 0006_inventory
Revises: 0005_products
"""
from alembic import op
import sqlalchemy as sa
revision="0006_inventory";down_revision="0005_products";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("inventories",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("business_id",sa.Uuid(),sa.ForeignKey("businesses.id"),nullable=False),sa.Column("product_id",sa.Uuid(),sa.ForeignKey("products.id"),nullable=False),sa.Column("quantity_on_hand",sa.Numeric(14,3),server_default="0",nullable=False),sa.UniqueConstraint("business_id","product_id",name="uq_inventories_business_product"),sa.UniqueConstraint("business_id","id",name="uq_inventories_business_id"),sa.CheckConstraint("quantity_on_hand >= 0",name="ck_inventories_nonnegative"));op.create_index("ix_inventories_business_quantity","inventories",["business_id","quantity_on_hand"])
 op.create_table("stock_movements",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("business_id",sa.Uuid(),nullable=False),sa.Column("inventory_id",sa.Uuid(),nullable=False),sa.Column("product_id",sa.Uuid(),nullable=False),sa.Column("movement_type",sa.String(32),nullable=False),sa.Column("quantity_delta",sa.Numeric(14,3),nullable=False),sa.Column("quantity_before",sa.Numeric(14,3),nullable=False),sa.Column("quantity_after",sa.Numeric(14,3),nullable=False),sa.Column("reason",sa.String(255),nullable=False),sa.Column("notes",sa.String(4000)),sa.Column("actor_user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.ForeignKeyConstraint(["business_id","inventory_id"],["inventories.business_id","inventories.id"]),sa.ForeignKeyConstraint(["business_id","product_id"],["products.business_id","products.id"]),sa.CheckConstraint("movement_type IN ('opening_balance','adjustment_in','adjustment_out','correction')",name="ck_stock_movements_type"));op.create_index("ix_stock_movements_business_created","stock_movements",["business_id","created_at"])
 if op.get_bind().dialect.name=="postgresql":
  op.execute("CREATE FUNCTION prevent_inventory_tenant_move() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.business_id IS DISTINCT FROM NEW.business_id THEN RAISE EXCEPTION 'Inventory tenant cannot be changed'; END IF; RETURN NEW; END $$");op.execute("CREATE TRIGGER inventories_immutable_tenant BEFORE UPDATE OF business_id ON inventories FOR EACH ROW EXECUTE FUNCTION prevent_inventory_tenant_move()");op.execute("CREATE TRIGGER stock_movements_immutable_tenant BEFORE UPDATE OF business_id ON stock_movements FOR EACH ROW EXECUTE FUNCTION prevent_inventory_tenant_move()")
def downgrade():
 if op.get_bind().dialect.name=="postgresql":op.execute("DROP TRIGGER stock_movements_immutable_tenant ON stock_movements");op.execute("DROP TRIGGER inventories_immutable_tenant ON inventories");op.execute("DROP FUNCTION prevent_inventory_tenant_move()")
 op.drop_table("stock_movements");op.drop_table("inventories")
