"""Immutable order invoice snapshots.
Revision ID: 0009_invoices
Revises: 0008_payments
"""
from alembic import op
import sqlalchemy as sa
revision='0009_invoices';down_revision='0008_payments';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('invoices',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.Column('business_id',sa.Uuid(),sa.ForeignKey('businesses.id'),nullable=False),sa.Column('order_id',sa.Uuid(),nullable=False),sa.Column('invoice_number',sa.String(64),nullable=False),sa.Column('status',sa.String(16),server_default='issued',nullable=False),sa.Column('issued_at',sa.DateTime(timezone=True),nullable=False),sa.Column('order_number',sa.String(64),nullable=False),sa.Column('customer_name',sa.String(160),nullable=False),sa.Column('customer_email',sa.String(320)),sa.Column('customer_address',sa.String(1000)),sa.Column('customer_tax_id',sa.String(100)),sa.Column('subtotal',sa.Numeric(14,2),nullable=False),sa.Column('tax_total',sa.Numeric(14,2),nullable=False),sa.Column('grand_total',sa.Numeric(14,2),nullable=False),sa.ForeignKeyConstraint(['business_id','order_id'],['orders.business_id','orders.id'],ondelete='RESTRICT'),sa.UniqueConstraint('business_id','invoice_number',name='uq_invoices_business_number'),sa.UniqueConstraint('business_id','order_id',name='uq_invoices_business_order'),sa.UniqueConstraint('business_id','id',name='uq_invoices_business_id'),sa.CheckConstraint("status IN ('issued')",name='ck_invoices_status'),sa.CheckConstraint('subtotal >= 0',name='ck_invoices_subtotal'),sa.CheckConstraint('tax_total >= 0',name='ck_invoices_tax_total'),sa.CheckConstraint('grand_total >= 0',name='ck_invoices_grand_total'))
 op.create_index('ix_invoices_business_status','invoices',['business_id','status']);op.create_index('ix_invoices_business_issued','invoices',['business_id','issued_at']);op.create_index('ix_invoices_business_customer','invoices',['business_id','customer_name'])
 op.create_table('invoice_items',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.Column('business_id',sa.Uuid(),nullable=False),sa.Column('invoice_id',sa.Uuid(),nullable=False),sa.Column('product_name',sa.String(160),nullable=False),sa.Column('product_sku',sa.String(64),nullable=False),sa.Column('quantity',sa.Numeric(14,3),nullable=False),sa.Column('unit_price',sa.Numeric(14,2),nullable=False),sa.Column('tax_rate',sa.Numeric(5,2),nullable=False),sa.Column('line_subtotal',sa.Numeric(14,2),nullable=False),sa.Column('line_tax',sa.Numeric(14,2),nullable=False),sa.Column('line_total',sa.Numeric(14,2),nullable=False),sa.ForeignKeyConstraint(['business_id','invoice_id'],['invoices.business_id','invoices.id'],ondelete='RESTRICT'),sa.CheckConstraint('quantity > 0',name='ck_invoice_items_quantity'),sa.CheckConstraint('unit_price >= 0',name='ck_invoice_items_unit_price'),sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100',name='ck_invoice_items_tax_rate'),sa.CheckConstraint('line_subtotal >= 0',name='ck_invoice_items_subtotal'),sa.CheckConstraint('line_tax >= 0',name='ck_invoice_items_tax'),sa.CheckConstraint('line_total >= 0',name='ck_invoice_items_total'))
 op.create_index('ix_invoice_items_invoice','invoice_items',['invoice_id'])
 if op.get_bind().dialect.name=='postgresql':
  op.execute("CREATE FUNCTION prevent_invoice_tenant_move() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.business_id IS DISTINCT FROM NEW.business_id THEN RAISE EXCEPTION 'Invoice tenant cannot be changed'; END IF; RETURN NEW; END $$");op.execute('CREATE TRIGGER invoices_immutable_tenant BEFORE UPDATE OF business_id ON invoices FOR EACH ROW EXECUTE FUNCTION prevent_invoice_tenant_move()');op.execute("CREATE FUNCTION prevent_invoice_item_tenant_move() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.business_id IS DISTINCT FROM NEW.business_id THEN RAISE EXCEPTION 'Invoice item tenant cannot be changed'; END IF; RETURN NEW; END $$");op.execute('CREATE TRIGGER invoice_items_immutable_tenant BEFORE UPDATE OF business_id ON invoice_items FOR EACH ROW EXECUTE FUNCTION prevent_invoice_item_tenant_move()')
def downgrade():
 if op.get_bind().dialect.name=='postgresql':
  op.execute('DROP TRIGGER invoice_items_immutable_tenant ON invoice_items');op.execute('DROP FUNCTION prevent_invoice_item_tenant_move()');op.execute('DROP TRIGGER invoices_immutable_tenant ON invoices');op.execute('DROP FUNCTION prevent_invoice_tenant_move()')
 op.drop_table('invoice_items');op.drop_table('invoices')
