import { useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../api/client";
import { Button, Card, Input, Table } from "../../components/ui";
import { Can } from "../team/permissions";
import { Dialog, Feedback } from "../team/shared";
import { errorMessage } from "../team/errors";

export type Inventory = { id: string; product_id: string; product_name: string; sku: string; unit_of_measure: string; quantity_on_hand: string; reorder_level: string | null; stock_status: "in_stock" | "low_stock" | "out_of_stock"; updated_at: string };
type InventoryPageResponse = { items: Inventory[]; total: number; page: number; page_size: number };
type Movement = { id: string; movement_type: string; quantity_delta: string; quantity_before: string; quantity_after: string; reason: string; notes: string | null; created_at: string };
type AdjustmentOperation = "opening_balance" | "increase" | "decrease";
export type InventoryAdjustmentTarget = Pick<Inventory, "product_id" | "product_name" | "unit_of_measure" | "quantity_on_hand">;

const inventoryKey = ["inventory"] as const;
const detailKey = (productId: string) => ["inventory", productId] as const;
const movementsKey = (productId: string) => ["inventory", productId, "movements"] as const;
const labels: Record<Inventory["stock_status"], string> = { in_stock: "In stock", low_stock: "Low stock", out_of_stock: "Out of stock" };
const badgeClasses: Record<Inventory["stock_status"], string> = { in_stock: "bg-green-50 text-green-700", low_stock: "bg-amber-50 text-amber-700", out_of_stock: "bg-red-50 text-red-700" };
const movementLabels: Record<string, string> = { opening_balance: "Opening balance", adjustment_in: "Increase", adjustment_out: "Decrease", correction: "Correction" };

export function StockStatus({ status }: { status: Inventory["stock_status"] }): JSX.Element { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${badgeClasses[status]}`}>{labels[status]}</span>; }

export function AdjustmentDialog({ inventory, close, openingBalanceOnly = false, onSuccess }: { inventory: InventoryAdjustmentTarget; close: () => void; openingBalanceOnly?: boolean; onSuccess?: (inventory: Inventory) => void }): JSX.Element {
  const cache = useQueryClient(); const [validation, setValidation] = useState(""); const [operation, setOperation] = useState<AdjustmentOperation>(openingBalanceOnly ? "opening_balance" : "increase"); const [quantity, setQuantity] = useState("");
  const adjustment = useMutation({ mutationFn: async (payload: { operation: AdjustmentOperation; quantity: string; reason: string; notes: string | null }) => (await api.post<Inventory>(`/inventory/${inventory.product_id}/adjust`, payload)).data, onSuccess: async result => { await Promise.all([cache.invalidateQueries({ queryKey: inventoryKey }), cache.invalidateQueries({ queryKey: detailKey(inventory.product_id) }), cache.invalidateQueries({ queryKey: movementsKey(inventory.product_id) })]); close(); onSuccess?.(result); } });
  const numericQuantity = Number(quantity); const current = Number(inventory.quantity_on_hand); const expected = operation === "decrease" ? current - (Number.isFinite(numericQuantity) ? numericQuantity : 0) : operation === "opening_balance" ? (Number.isFinite(numericQuantity) ? numericQuantity : 0) : current + (Number.isFinite(numericQuantity) ? numericQuantity : 0);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const reason = String(form.get("reason") ?? "").trim(); if (!Number.isFinite(numericQuantity) || numericQuantity <= 0) { setValidation("Enter a quantity greater than zero."); return; } if (reason.length < 2) { setValidation("Enter a reason with at least two characters."); return; } setValidation(""); adjustment.mutate({ operation, quantity, reason, notes: String(form.get("notes") ?? "").trim() || null }); };
  return <Dialog title={`${openingBalanceOnly ? "Initialize" : "Adjust"} ${inventory.product_name}`} close={close}><form noValidate onSubmit={submit} className="space-y-4"><p className="text-sm text-gray-600">Current quantity: <strong>{openingBalanceOnly ? "0" : inventory.quantity_on_hand} {inventory.unit_of_measure}</strong></p>{openingBalanceOnly ? <p className="text-sm text-gray-600">Operation: <strong>Opening balance</strong></p> : <label className="label">Operation<select className="field" value={operation} onChange={event => setOperation(event.target.value as AdjustmentOperation)}><option value="opening_balance">Opening balance</option><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label>}<Input label="Quantity" name="quantity" type="number" min="0.001" step="0.001" value={quantity} onChange={event => setQuantity(event.target.value)} required /><Input label="Reason" name="reason" required /><label className="label">Notes (optional)<textarea className="field min-h-20" name="notes" /></label><p className={`text-sm ${expected < 0 ? "text-red-600" : "text-gray-600"}`}>Expected resulting quantity: {Number.isFinite(expected) ? expected : "—"} {inventory.unit_of_measure}</p><Feedback error={validation || (adjustment.isError ? errorMessage(adjustment.error) : undefined)} /><div className="flex gap-3"><Button disabled={adjustment.isPending}>{adjustment.isPending ? "Adjusting…" : "Save adjustment"}</Button><button type="button" onClick={close} disabled={adjustment.isPending}>Cancel</button></div></form></Dialog>;
}

export function InventoryPage(): JSX.Element {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [adjusting, setAdjusting] = useState<Inventory | null>(null);
  const inventory = useQuery({ queryKey: [...inventoryKey, search, status, page], queryFn: async () => (await api.get<InventoryPageResponse>("/inventory", { params: { search, status: status || undefined, page, page_size: 20 } })).data });
  const changeSearch = (value: string) => { setSearch(value); setPage(1); }; const changeStatus = (value: string) => { setStatus(value); setPage(1); };
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Inventory</h1><p className="mt-1 text-sm text-gray-500">Monitor stock quantities and record inventory adjustments.</p></div><Card><div className="mb-5 grid gap-3 sm:grid-cols-2"><Input label="Search inventory" type="search" placeholder="Product name or SKU" value={search} onChange={event => changeSearch(event.target.value)} /><label className="label">Stock status<select className="field" value={status} onChange={event => changeStatus(event.target.value)}><option value="">All stock statuses</option><option value="in_stock">In stock</option><option value="low_stock">Low stock</option><option value="out_of_stock">Out of stock</option></select></label></div>{inventory.isPending ? <p role="status">Loading inventory…</p> : inventory.isError ? <><Feedback error={errorMessage(inventory.error)} /><button onClick={() => void inventory.refetch()}>Retry</button></> : <><Table columns={["Product", "SKU", "On hand", "Unit", "Reorder level", "Stock status", "Last updated", "Actions"]}>{inventory.data.items.map(item => <tr key={item.id}><td className="px-4 py-4"><Link className="font-medium text-blue-700" to={`/inventory/${item.product_id}`}>{item.product_name}</Link></td><td className="px-4 py-4">{item.sku}</td><td className="px-4 py-4">{item.quantity_on_hand}</td><td className="px-4 py-4">{item.unit_of_measure}</td><td className="px-4 py-4">{item.reorder_level ?? "—"}</td><td className="px-4 py-4"><StockStatus status={item.stock_status} /></td><td className="px-4 py-4 text-xs text-gray-500">{new Date(item.updated_at).toLocaleString()}</td><td className="px-4 py-4"><div className="flex gap-3 text-xs font-medium text-blue-700"><Link to={`/inventory/${item.product_id}`}>View</Link><Can permission="inventory.adjust"><button onClick={() => setAdjusting(item)}>Adjust</button></Can></div></td></tr>)}</Table>{inventory.data.items.length === 0 && <p className="py-10 text-center text-sm text-gray-500">No inventory items match these filters.</p>}<div className="mt-5 flex justify-between text-sm"><span>{inventory.data.total} items · Page {page}</span><div className="flex gap-3"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button disabled={page * inventory.data.page_size >= inventory.data.total} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</Card>{adjusting && <AdjustmentDialog inventory={adjusting} close={() => setAdjusting(null)} />}</div>;
}

export function InventoryDetailsPage(): JSX.Element {
  const { productId = "" } = useParams(); const [adjusting, setAdjusting] = useState(false); const inventory = useQuery({ queryKey: detailKey(productId), queryFn: async () => (await api.get<Inventory>(`/inventory/${productId}`)).data }); const movements = useQuery({ queryKey: movementsKey(productId), queryFn: async () => (await api.get<Movement[]>(`/inventory/${productId}/movements`)).data });
  if (inventory.isPending) return <p role="status">Loading inventory…</p>; if (inventory.isError) return <Feedback error={errorMessage(inventory.error)} />; const item = inventory.data;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="text-sm font-medium text-blue-700" to="/inventory">← Inventory</Link><h1 className="mt-3 text-2xl font-semibold">{item.product_name}</h1><p className="mt-1 text-sm text-gray-500">SKU: {item.sku}</p></div><Can permission="inventory.adjust"><Button onClick={() => setAdjusting(true)}>Adjust stock</Button></Can></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Card><h2 className="mb-3 font-semibold">Current stock</h2><p className="text-3xl font-semibold">{item.quantity_on_hand}</p><p className="mt-1 text-sm text-gray-500">{item.unit_of_measure}</p></Card><Card><h2 className="mb-3 font-semibold">Stock status</h2><StockStatus status={item.stock_status} /><p className="mt-3 text-sm text-gray-500">Reorder level: {item.reorder_level ?? "Not set"}</p></Card><Card><h2 className="mb-3 font-semibold">Inventory metadata</h2><p className="text-sm text-gray-600">Last updated<br /><span className="font-medium text-gray-900">{new Date(item.updated_at).toLocaleString()}</span></p></Card></div><Card><h2 className="mb-4 font-semibold">Stock movement history</h2>{movements.isPending ? <p role="status">Loading movement history…</p> : movements.isError ? <><Feedback error={errorMessage(movements.error)} /><button onClick={() => void movements.refetch()}>Retry</button></> : movements.data.length === 0 ? <p className="text-sm text-gray-500">No stock movements recorded.</p> : <Table columns={["When", "Type", "Delta", "Before", "After", "Reason"]}>{movements.data.map(movement => <tr key={movement.id}><td className="px-4 py-4 text-xs text-gray-500">{new Date(movement.created_at).toLocaleString()}</td><td className="px-4 py-4">{movementLabels[movement.movement_type] ?? movement.movement_type}</td><td className="px-4 py-4">{movement.quantity_delta}</td><td className="px-4 py-4">{movement.quantity_before}</td><td className="px-4 py-4">{movement.quantity_after}</td><td className="px-4 py-4">{movement.reason}{movement.notes ? <div className="mt-1 text-xs text-gray-500">{movement.notes}</div> : null}</td></tr>)}</Table>}</Card>{adjusting && <AdjustmentDialog inventory={item} close={() => setAdjusting(false)} />}</div>;
}
