import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { PropsWithChildren } from "react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthContext } from "../auth/auth-store";
import { api } from "../../api/client";
import { InventoryDetailsPage, InventoryPage } from "./inventory-page";

vi.mock("../../api/client", () => ({ api: { get: vi.fn(), post: vi.fn() } }));
const item = { id: "i1", product_id: "p1", product_name: "Widget", sku: "WID-001", unit_of_measure: "piece", quantity_on_hand: "5.000", reorder_level: "10.000", stock_status: "low_stock", updated_at: "2026-01-01T00:00:00Z" } as const;
const movement = { id: "m1", movement_type: "adjustment_in", quantity_delta: "2.000", quantity_before: "3.000", quantity_after: "5.000", reason: "Delivery", notes: null, created_at: "2026-01-01T00:00:00Z" } as const;
function Wrapper({ children, grants = ["inventory.view", "inventory.adjust"] }: PropsWithChildren<{ grants?: string[] }>): JSX.Element { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return <MemoryRouter initialEntries={["/inventory/p1"]}><QueryClientProvider client={client}><AuthContext.Provider value={{ session: null, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
beforeEach(() => { vi.clearAllMocks(); HTMLDialogElement.prototype.showModal = function () { this.open = true; }; HTMLDialogElement.prototype.close = function () { this.open = false; }; vi.mocked(api.get).mockImplementation(async (url: string) => ({ data: url.includes("movements") ? [movement] : url === "/inventory" ? { items: [item], total: 1, page: 1, page_size: 20 } : item })); vi.mocked(api.post).mockResolvedValue({ data: { ...item, quantity_on_hand: "7.000" } }); }); afterEach(cleanup);
describe("inventory management UX", () => {
  it("renders inventory data, stock status, and permission-gated adjustments", async () => { render(<Wrapper grants={["inventory.view"]}><InventoryPage /></Wrapper>); expect(await screen.findByText("Widget")).toBeTruthy(); expect(screen.getAllByText("Low stock")).toHaveLength(2); expect(screen.queryByText("Adjust")).toBeNull(); });
  it("renders loading and empty inventory states", async () => { let resolve: ((value: unknown) => void) | undefined; vi.mocked(api.get).mockReturnValueOnce(new Promise(resolveValue => { resolve = resolveValue; }) as never); render(<Wrapper><InventoryPage /></Wrapper>); expect(screen.getByText("Loading inventory…")).toBeTruthy(); resolve?.({ data: { items: [], total: 0, page: 1, page_size: 20 } }); expect(await screen.findByText("No inventory items match these filters.")).toBeTruthy(); });
  it("sends search and stock-status filters to the inventory API", async () => { render(<Wrapper><InventoryPage /></Wrapper>); await screen.findByText("Widget"); fireEvent.change(screen.getByLabelText("Search inventory"), { target: { value: "wid" } }); fireEvent.change(screen.getByLabelText("Stock status"), { target: { value: "low_stock" } }); await waitFor(() => expect(api.get).toHaveBeenCalledWith("/inventory", expect.objectContaining({ params: expect.objectContaining({ search: "wid", status: "low_stock", page: 1 }) }))); });
  it("renders details and history, validates then submits an adjustment and refreshes queries", async () => { render(<Wrapper><Routes><Route path="/inventory/:productId" element={<InventoryDetailsPage />} /></Routes></Wrapper>); expect(await screen.findByText("Stock movement history")).toBeTruthy(); expect(screen.getByText("Increase")).toBeTruthy(); fireEvent.click(screen.getByText("Adjust stock")); fireEvent.click(screen.getByText("Save adjustment")); expect(await screen.findByText("Enter a quantity greater than zero.")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Quantity"), { target: { value: "2" } }); fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Delivery" } }); fireEvent.click(screen.getByText("Save adjustment")); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/inventory/p1/adjust", expect.objectContaining({ operation: "increase", quantity: "2", reason: "Delivery" }))); });
  it("shows an insufficient-stock response without closing the adjustment dialog", async () => { vi.mocked(api.post).mockRejectedValueOnce(Object.assign(new Error("conflict"), { isAxiosError: true, response: { data: { detail: "Stock cannot fall below zero." } } })); render(<Wrapper><Routes><Route path="/inventory/:productId" element={<InventoryDetailsPage />} /></Routes></Wrapper>); await screen.findByText("Stock movement history"); fireEvent.click(screen.getByText("Adjust stock")); fireEvent.change(screen.getByLabelText("Operation"), { target: { value: "decrease" } }); fireEvent.change(screen.getByLabelText("Quantity"), { target: { value: "8" } }); fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Shipment" } }); fireEvent.click(screen.getByText("Save adjustment")); expect(await screen.findByText("Stock cannot fall below zero.")).toBeTruthy(); expect(screen.getAllByRole("dialog")).toHaveLength(2); });
});
