import { useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import { isAxiosError } from "axios";
import { Button, Card, Input } from "../components/ui";
import { useAuth } from "../features/auth/use-auth";

function AuthFrame({ title, children }: { title: string; children: ReactNode }): JSX.Element { return <main className="flex min-h-screen items-center justify-center p-4"><Card className="w-full max-w-md"><div className="mb-6"><p className="text-xl font-bold">Business<span className="text-[#2563EB]">OS</span></p><h1 className="mt-4 text-2xl font-semibold">{title}</h1></div>{children}</Card></main>; }
const message = (error: unknown): string => isAxiosError<{ detail?: string }>(error) ? error.response?.data.detail ?? "Something went wrong." : "Something went wrong.";
export function LoginPage(): JSX.Element { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); setError(""); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/"); } catch (err) { setError(message(err)); } finally { setLoading(false); } }; return <AuthFrame title="Sign in to your workspace"><form onSubmit={(event) => void submit(event)} className="space-y-4"><Input label="Email" name="email" type="email" required autoComplete="email"/><Input label="Password" name="password" type="password" required autoComplete="current-password"/>{error && <p className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</Button></form><p className="mt-5 text-sm text-[#6B7280]">New to BusinessOS? <Link className="font-medium text-[#2563EB]" to="/register">Create a business account</Link></p></AuthFrame>; }
export function RegisterPage(): JSX.Element { const { register } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password")); if (password.length < 12) { setError("Use a password of at least 12 characters."); return; } setLoading(true); setError(""); try { await register(String(data.get("businessName")), String(data.get("fullName")), String(data.get("email")), password); navigate("/"); } catch (err) { setError(message(err)); } finally { setLoading(false); } }; return <AuthFrame title="Create your business account"><form onSubmit={(event) => void submit(event)} className="space-y-4"><Input label="Business name" name="businessName" required minLength={2}/><Input label="Your name" name="fullName" required minLength={2}/><Input label="Work email" name="email" type="email" required/><Input label="Password" name="password" type="password" required minLength={12} autoComplete="new-password"/>{error && <p className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={loading}>{loading ? "Creating account…" : "Create account"}</Button></form><p className="mt-5 text-sm text-[#6B7280]">Already have an account? <Link className="font-medium text-[#2563EB]" to="/login">Sign in</Link></p></AuthFrame>; }
