import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router-dom";
import { api } from "../api/client";
import { AuthContext } from "../features/auth/auth-store";
import { DashboardPage } from "./dashboard-page";

vi.mock("../api/client", () => ({ api: { get: vi.fn() } }));
const data = { range: "30d", period_start: "2026-08-12T00:00:00Z", summary: { total_customers: 12, total_products: 8, total_orders: 7, total_invoices: 6 }, orders: { draft_count: 2, confirmed_count: 4, cancelled_count: 1, period_confirmed_count: 3, period_confirmed_order_value: "1234.56", period_average_confirmed_order_value: "411.52" }, payments: { completed_count: 3, pending_count: 2, failed_count: 1, cancelled_count: 0, period_completed_amount: "500.10", period_pending_amount: "99.90", outstanding_amount: "734.46" }, inventory: { tracked_products: 8, in_stock_count: 5, low_stock_count: 2, out_of_stock_count: 1, low_stock_products: [{ product_id: "product-1", product_name: "Widget", sku: "SKU-1", quantity: "2.000", reorder_threshold: "5.000", stock_status: "low_stock" }] }, customers: { total: 12, active: 10, inactive: 2 }, recent_activity: { orders: [{ id: "order-1", reference: "SO-1", status: "confirmed", amount: "200.00", occurred_at: "2026-09-01T10:00:00Z" }], payments: [{ id: "payment-1", reference: "PAY-1", status: "completed", amount: "100.00", occurred_at: "2026-09-01T11:00:00Z" }], invoices: [{ id: "invoice-1", reference: "INV-1", status: "issued", amount: "200.00", occurred_at: "2026-09-01T12:00:00Z" }] } };
function Wrap({ allowed = true }: { allowed?: boolean }) { const query = new QueryClient({ defaultOptions: { queries: { retry: false } } }); const grants = allowed ? ["reports.view"] : []; return <MemoryRouter><QueryClientProvider client={query}><AuthContext.Provider value={{ session: { user: { id: "u", email: "a@example.com", full_name: "A", business_id: "b", roles: [], permissions: grants }, business: { id: "b", name: "Alpha", slug: "alpha" }, access_token: "x", refresh_token: "y", token_type: "bearer" }, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}><DashboardPage /></AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.get).mockResolvedValue({ data }); }); afterEach(cleanup);
describe("analytics dashboard", () => {
 it("fetches the default range and renders all server metrics", async () => { render(<Wrap/>); expect(await screen.findByText("₹1234.56")).toBeTruthy(); expect(api.get).toHaveBeenCalledWith("/analytics/dashboard", { params: { range: "30d" } }); expect(screen.getByText("₹500.10")).toBeTruthy(); expect(screen.getByText("₹734.46")).toBeTruthy(); expect(screen.getAllByText("12").length).toBeGreaterThan(0); expect(screen.getByText("Widget")).toBeTruthy(); expect(screen.getByText("low stock")).toBeTruthy(); expect(screen.getByText("SO-1")).toBeTruthy(); expect(screen.getByText("PAY-1")).toBeTruthy(); expect(screen.getByText("INV-1")).toBeTruthy(); });
 it("uses the selected range in a distinct request", async () => { render(<Wrap/>); await screen.findByText("₹1234.56"); fireEvent.change(screen.getByLabelText("Reporting period"), { target: { value: "7d" } }); await waitFor(() => expect(api.get).toHaveBeenCalledWith("/analytics/dashboard", { params: { range: "7d" } })); });
 it("renders loading, error with retry, and zero-data states", async () => { vi.mocked(api.get).mockImplementation(() => new Promise(() => {})); const loading = render(<Wrap/>); expect(screen.getByRole("status").textContent).toContain("Loading dashboard analytics…"); loading.unmount(); vi.mocked(api.get).mockClear(); vi.mocked(api.get).mockRejectedValue(new Error("Network")); const failed = render(<Wrap/>); expect(await screen.findByText("Unable to complete the request. Please try again.")).toBeTruthy(); fireEvent.click(screen.getByText("Retry")); await waitFor(() => expect(api.get).toHaveBeenCalledTimes(2)); failed.unmount(); vi.mocked(api.get).mockResolvedValue({ data: { ...data, summary: { total_customers: 0, total_products: 0, total_orders: 0, total_invoices: 0 }, inventory: { tracked_products: 0, in_stock_count: 0, low_stock_count: 0, out_of_stock_count: 0, low_stock_products: [] }, customers: { total: 0, active: 0, inactive: 0 }, recent_activity: { orders: [], payments: [], invoices: [] } } }); render(<Wrap/>); expect(await screen.findByText("No low-stock products.")).toBeTruthy(); expect(screen.getByText("No recent orders.")).toBeTruthy(); });
 it("does not fetch or expose analytics without reports.view", () => { render(<Wrap allowed={false}/>); expect(screen.getByText("You do not have permission to view business analytics.")).toBeTruthy(); expect(api.get).not.toHaveBeenCalled(); expect(screen.queryByText("₹1234.56")).toBeNull(); });
});
