import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";
import { Card, Table } from "../components/ui";
import { useAuth } from "../features/auth/use-auth";
import { Feedback } from "../features/team/shared";
import { errorMessage } from "../features/team/errors";

type Range = "7d" | "30d" | "90d";
type LowStockProduct = { product_id: string; product_name: string; sku: string; quantity: string; reorder_threshold: string | null; stock_status: "low_stock" | "out_of_stock" };
type RecentRecord = { id: string; reference: string; status: string; amount: string; occurred_at: string };
type DashboardAnalytics = {
 range: Range; period_start: string;
 summary: { total_customers: number; total_products: number; total_orders: number; total_invoices: number };
 orders: { draft_count: number; confirmed_count: number; cancelled_count: number; period_confirmed_count: number; period_confirmed_order_value: string; period_average_confirmed_order_value: string };
 payments: { completed_count: number; pending_count: number; failed_count: number; cancelled_count: number; period_completed_amount: string; period_pending_amount: string; outstanding_amount: string };
 inventory: { tracked_products: number; in_stock_count: number; low_stock_count: number; out_of_stock_count: number; low_stock_products: LowStockProduct[] };
 customers: { total: number; active: number; inactive: number };
 recent_activity: { orders: RecentRecord[]; payments: RecentRecord[]; invoices: RecentRecord[] };
};
const money = (value: string) => `₹${value}`;
const periodLabels: Record<Range, string> = { "7d": "Last 7 days", "30d": "Last 30 days", "90d": "Last 90 days" };
const stockClasses = { low_stock: "bg-amber-50 text-amber-700", out_of_stock: "bg-red-50 text-red-700" };
function Metric({ label, value, detail }: { label: string; value: string | number; detail?: string }): JSX.Element { return <Card className="p-5"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold text-gray-900">{value}</p>{detail && <p className="mt-1 text-xs text-gray-500">{detail}</p>}</Card>; }
function Activity({ title, records, path }: { title: string; records: RecentRecord[]; path: string }): JSX.Element { return <div><h3 className="mb-3 font-semibold">{title}</h3>{records.length ? <ul className="divide-y divide-gray-100">{records.map(record => <li key={record.id} className="flex items-center justify-between gap-3 py-3 text-sm"><div><Link className="font-medium text-blue-700" to={`/${path}/${record.id}`}>{record.reference}</Link><p className="text-xs text-gray-500">{new Date(record.occurred_at).toLocaleString()} · {record.status.replace("_", " ")}</p></div><span className="font-medium">{money(record.amount)}</span></li>)}</ul> : <p className="text-sm text-gray-500">No recent {title.toLowerCase()}.</p>}</div>; }

export function DashboardPage(): JSX.Element {
 const { session, can } = useAuth(); const allowed = can("reports.view"); const [range, setRange] = useState<Range>("30d");
 const analytics = useQuery({ queryKey: ["analytics", "dashboard", range], enabled: allowed, queryFn: async () => (await api.get<DashboardAnalytics>("/analytics/dashboard", { params: { range } })).data });
 if (!allowed) return <div className="space-y-4"><h2 className="text-2xl font-semibold">Dashboard</h2><Feedback error="You do not have permission to view business analytics." /></div>;
 if (analytics.isPending) return <p role="status">Loading dashboard analytics…</p>;
 if (analytics.isError) return <div className="space-y-3"><Feedback error={errorMessage(analytics.error)} /><button className="text-sm font-medium text-blue-700" onClick={() => void analytics.refetch()}>Retry</button></div>;
 const data = analytics.data;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-blue-700">Business overview</p><h2 className="mt-1 text-2xl font-semibold">{session?.business.name}</h2><p className="mt-1 text-sm text-gray-500">Current business health and activity from server analytics.</p></div><label className="label min-w-40">Reporting period<select aria-label="Reporting period" className="field" value={range} onChange={event => setRange(event.target.value as Range)}><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label></div>
 <section><h3 className="mb-3 font-semibold">Lifetime summary</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Customers" value={data.summary.total_customers}/><Metric label="Products" value={data.summary.total_products}/><Metric label="Orders" value={data.summary.total_orders}/><Metric label="Invoices" value={data.summary.total_invoices}/></div></section>
 <section><h3 className="mb-3 font-semibold">Orders · {periodLabels[range]}</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Confirmed Order Value" value={money(data.orders.period_confirmed_order_value)} detail={`${data.orders.period_confirmed_count} confirmed in period`}/><Metric label="Average Confirmed Order Value" value={money(data.orders.period_average_confirmed_order_value)}/><Metric label="All Order Statuses" value={data.orders.confirmed_count} detail={`${data.orders.draft_count} draft · ${data.orders.cancelled_count} cancelled`}/></div></section>
 <section><h3 className="mb-3 font-semibold">Payments · {periodLabels[range]}</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Completed Payment Amount" value={money(data.payments.period_completed_amount)} detail={`${data.payments.completed_count} completed overall`}/><Metric label="Pending Payment Amount" value={money(data.payments.period_pending_amount)} detail={`${data.payments.pending_count} pending overall`}/><Metric label="Outstanding Balance" value={money(data.payments.outstanding_amount)} detail={`${data.payments.failed_count} failed · ${data.payments.cancelled_count} cancelled`}/></div></section>
 <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><h3 className="mb-4 font-semibold">Inventory overview</h3><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-gray-500">Tracked</p><p className="text-xl font-semibold">{data.inventory.tracked_products}</p></div><div><p className="text-xs text-gray-500">In stock</p><p className="text-xl font-semibold text-green-700">{data.inventory.in_stock_count}</p></div><div><p className="text-xs text-gray-500">Low stock</p><p className="text-xl font-semibold text-amber-700">{data.inventory.low_stock_count}</p></div><div><p className="text-xs text-gray-500">Out of stock</p><p className="text-xl font-semibold text-red-700">{data.inventory.out_of_stock_count}</p></div></div><Table columns={["Product", "SKU", "Quantity", "Reorder threshold", "Status"]}>{data.inventory.low_stock_products.map(product => <tr key={product.product_id}><td className="px-4 py-3"><Link className="font-medium text-blue-700" to={`/inventory/${product.product_id}`}>{product.product_name}</Link></td><td className="px-4 py-3">{product.sku}</td><td className="px-4 py-3">{product.quantity}</td><td className="px-4 py-3">{product.reorder_threshold ?? "—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${stockClasses[product.stock_status]}`}>{product.stock_status.replaceAll("_", " ")}</span></td></tr>)}</Table>{!data.inventory.low_stock_products.length && <p className="py-6 text-center text-sm text-gray-500">No low-stock products.</p>}</Card><Card><h3 className="mb-4 font-semibold">Customers</h3><div className="space-y-4"><Metric label="Total customers" value={data.customers.total}/><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-gray-500">Active</p><p className="text-xl font-semibold text-green-700">{data.customers.active}</p></div><div><p className="text-xs text-gray-500">Inactive</p><p className="text-xl font-semibold text-gray-700">{data.customers.inactive}</p></div></div></div></Card></div>
 <Card><h3 className="mb-4 font-semibold">Recent business activity</h3><div className="grid gap-6 lg:grid-cols-3"><Activity title="Orders" records={data.recent_activity.orders} path="orders"/><Activity title="Payments" records={data.recent_activity.payments} path="payments"/><Activity title="Invoices" records={data.recent_activity.invoices} path="invoices"/></div></Card></div>;
}
