import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { AuthContext } from "../auth/auth-store";
import { api } from "../../api/client";
import { AppLayout } from "../../layouts/app-layout";
import { PaymentDetails, PaymentEditor, PaymentsPage } from "./payments-page";

vi.mock("../../api/client", () => ({ api: { get: vi.fn(), request: vi.fn() } }));
const payment = { id: "pay-1", order_id: "order-1", payment_number: "PAY-100", amount: "60.00", payment_method: "bank_transfer", status: "pending", paid_at: "2026-01-01T10:00:00Z", external_reference: "TX-1", notes: "Received", paid_amount: "60.00", remaining_balance: "40.00", payment_state: "partially_paid", created_at: "2026-01-01T10:00:00Z", updated_at: "2026-01-01T10:00:00Z" };
function Wrap({ children, grants = ["payments.view", "payments.create", "payments.update"], initial = "/payments/pay-1" }: { children: React.ReactNode; grants?: string[]; initial?: string }) { const query = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return <MemoryRouter initialEntries={[initial]}><QueryClientProvider client={query}><AuthContext.Provider value={{ session: { user: { id: "u", email: "a@example.com", full_name: "A", business_id: "b", roles: [], permissions: grants }, business: { id: "b", name: "Alpha", slug: "alpha" }, access_token: "x", refresh_token: "y", token_type: "bearer" }, isLoading: false, can: permission => grants.includes(permission), login: async () => {}, register: async () => {}, logout: async () => {} }}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
beforeEach(() => { vi.clearAllMocks(); HTMLDialogElement.prototype.showModal = function () { this.open = true; }; HTMLDialogElement.prototype.close = function () { this.open = false; }; vi.mocked(api.get).mockImplementation(async (url: string) => ({ data: url === "/payments" ? { items: [payment], total: 1, page: 1, page_size: 20 } : url === "/orders" ? { items: [{ id: "order-1", order_number: "SO-1", status: "confirmed", grand_total: "100.00" }] } : payment })); vi.mocked(api.request).mockResolvedValue({ data: { ...payment, status: "completed" } }); });
afterEach(cleanup);

describe("payments UX", () => {
  it("renders list, amount, status, and permission-gated create", async () => { render(<Wrap grants={["payments.view"]}><PaymentsPage /></Wrap>); expect(await screen.findByText("PAY-100")).toBeTruthy(); expect(screen.getByText("₹60.00")).toBeTruthy(); expect(screen.getByText("pending")).toBeTruthy(); expect(screen.queryByText("Create payment")).toBeNull(); });
  it("renders loading, empty, and error states", async () => { vi.mocked(api.get).mockImplementation(() => new Promise(() => {})); const { unmount } = render(<Wrap><PaymentsPage /></Wrap>); expect(screen.getByRole("status").textContent).toContain("Loading payments…"); unmount(); vi.mocked(api.get).mockResolvedValue({ data: { items: [], total: 0, page: 1, page_size: 20 } }); const empty = render(<Wrap><PaymentsPage /></Wrap>); expect(await screen.findByText("No payments match this status.")).toBeTruthy(); empty.unmount(); vi.mocked(api.get).mockRejectedValue(new Error("Network failed")); render(<Wrap><PaymentsPage /></Wrap>); expect(await screen.findByText("Unable to complete the request. Please try again.")).toBeTruthy(); });
  it("validates incomplete payment creation input", async () => { render(<Wrap><PaymentEditor /></Wrap>); await screen.findByRole("combobox", { name: "Confirmed order" }); fireEvent.submit(screen.getByRole("button", { name: "Create payment" }).closest("form")!); expect(await screen.findByText("Choose an order, enter a reference, and enter a positive decimal amount.")).toBeTruthy(); });
  it("shows server-derived balances and only offers pending completion with permission", async () => { render(<Wrap><Routes><Route path="/payments/:paymentId" element={<PaymentDetails />} /></Routes></Wrap>); expect(await screen.findByText("₹40.00")).toBeTruthy(); expect(screen.getByText("partially paid")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Complete payment" })); fireEvent.click((await screen.findAllByRole("button", { name: "Complete payment" }))[1]); await waitFor(() => expect(api.request).toHaveBeenCalledWith(expect.objectContaining({ method: "patch", url: "/payments/pay-1" }))); cleanup(); vi.mocked(api.get).mockResolvedValue({ data: { ...payment, status: "completed" } }); render(<Wrap grants={["payments.view"]}><Routes><Route path="/payments/:paymentId" element={<PaymentDetails />} /></Routes></Wrap>); await screen.findByText("PAY-100"); expect(screen.queryByRole("button", { name: "Complete payment" })).toBeNull(); });
  it("gates update and navigation by permissions", async () => { render(<Wrap grants={["payments.view"]}><Routes><Route path="/payments/:paymentId" element={<PaymentDetails />} /></Routes></Wrap>); await screen.findByText("PAY-100"); expect(screen.queryByRole("button", { name: "Complete payment" })).toBeNull(); cleanup(); render(<Wrap grants={["payments.view"]} initial="/"><Routes><Route path="/" element={<AppLayout />}><Route index element={<p>Home</p>} /></Route></Routes></Wrap>); expect(screen.getByText("Payments")).toBeTruthy(); cleanup(); render(<Wrap grants={[]} initial="/"><Routes><Route path="/" element={<AppLayout />}><Route index element={<p>Home</p>} /></Route></Routes></Wrap>); expect(screen.queryByText("Payments")).toBeNull(); });
});
