import { useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../api/client";
import { Button, Card, Input, Table } from "../../components/ui";
import { Can } from "../team/permissions";
import { Dialog, Feedback } from "../team/shared";
import { errorMessage } from "../team/errors";

type PaymentStatus = "pending" | "completed" | "failed" | "cancelled";
type PaymentState = "unpaid" | "partially_paid" | "paid";
type Payment = { id: string; order_id: string; payment_number: string; amount: string; payment_method: string; status: PaymentStatus; paid_at: string; external_reference: string | null; notes: string | null; paid_amount: string; remaining_balance: string; payment_state: PaymentState; created_at: string; updated_at: string };
type PaymentPage = { items: Payment[]; total: number; page: number; page_size: number };
type Order = { id: string; order_number: string; status: "draft" | "confirmed" | "cancelled"; grand_total: string };
type PaymentInput = { order_id: string; payment_number: string; amount: string; payment_method: string; status: PaymentStatus; external_reference: string | null; notes: string | null };

const paymentKey = ["payments"] as const;
const detailKey = (paymentId: string) => ["payment", paymentId] as const;
const decimalPattern = /^\d+(?:\.\d{1,2})?$/;
const statusClasses: Record<PaymentStatus, string> = { pending: "bg-amber-50 text-amber-700", completed: "bg-green-50 text-green-700", failed: "bg-red-50 text-red-700", cancelled: "bg-gray-100 text-gray-700" };
const stateClasses: Record<PaymentState, string> = { unpaid: "bg-gray-100 text-gray-700", partially_paid: "bg-blue-50 text-blue-700", paid: "bg-green-50 text-green-700" };
const money = (value: string) => `₹${value}`;

export function PaymentStatusBadge({ status }: { status: PaymentStatus }): JSX.Element { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${statusClasses[status]}`}>{status}</span>; }
function PaymentStateBadge({ state }: { state: PaymentState }): JSX.Element { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${stateClasses[state]}`}>{state.replace("_", " ")}</span>; }

function useConfirmedOrders() { return useQuery({ queryKey: ["orders", "payment-options"], queryFn: async () => (await api.get<{ items: Order[] }>("/orders", { params: { status: "confirmed", page_size: 100 } })).data.items }); }

function PaymentForm({ close, payment }: { close?: () => void; payment?: Payment }): JSX.Element {
  const navigate = useNavigate(); const cache = useQueryClient(); const orders = useConfirmedOrders(); const [validation, setValidation] = useState(""); const [form, setForm] = useState({ order_id: "", payment_number: "", amount: "", payment_method: "cash", status: "completed" as PaymentStatus, external_reference: payment?.external_reference ?? "", notes: payment?.notes ?? "" }); const editing = Boolean(payment);
  const mutation = useMutation({ mutationFn: async (payload: PaymentInput | Partial<PaymentInput>) => (await api.request<Payment>({ method: editing ? "patch" : "post", url: editing ? `/payments/${payment?.id}` : "/payments", data: payload })).data, onSuccess: async (saved) => { await Promise.all([cache.invalidateQueries({ queryKey: paymentKey }), cache.invalidateQueries({ queryKey: detailKey(saved.id) }), cache.invalidateQueries({ queryKey: ["orders"] })]); if (close) close(); else navigate(`/payments/${saved.id}`); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const amount = form.amount.trim(); const notes = form.notes.trim() || null; const reference = form.external_reference.trim() || null; if (editing) { mutation.mutate({ status: "completed", notes, external_reference: reference }); return; } const orderId = form.order_id; const number = form.payment_number.trim(); if (!orderId || !number || !decimalPattern.test(amount) || amount === "0" || /^0\.0*$/.test(amount)) { setValidation("Choose an order, enter a reference, and enter a positive decimal amount."); return; } setValidation(""); mutation.mutate({ order_id: orderId, payment_number: number, amount, payment_method: form.payment_method, status: form.status, external_reference: reference, notes }); };
  return <form noValidate onSubmit={submit} className="space-y-4">{editing ? <><p className="text-sm text-gray-600">Complete pending payment <strong>{payment?.payment_number}</strong> for {money(payment?.amount ?? "0.00")}.</p></> : <><label className="label">Confirmed order<select className="field" name="order_id" value={form.order_id} onChange={event => setForm(current => ({ ...current, order_id: event.target.value }))}><option value="">Select order</option>{(orders.data ?? []).map(order => <option key={order.id} value={order.id}>{order.order_number} · {money(order.grand_total)}</option>)}</select></label><Input label="Payment reference" name="payment_number" value={form.payment_number} onChange={event => setForm(current => ({ ...current, payment_number: event.target.value }))} required /><Input label="Amount" name="amount" inputMode="decimal" placeholder="0.00" value={form.amount} onChange={event => setForm(current => ({ ...current, amount: event.target.value }))} required /><label className="label">Method<select className="field" name="payment_method" value={form.payment_method} onChange={event => setForm(current => ({ ...current, payment_method: event.target.value }))}><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="upi">UPI</option><option value="other">Other</option></select></label><label className="label">Status<select className="field" name="status" value={form.status} onChange={event => setForm(current => ({ ...current, status: event.target.value as PaymentStatus }))}><option value="completed">Completed</option><option value="pending">Pending</option></select></label></>}<Input label="External reference (optional)" name="external_reference" value={form.external_reference} onChange={event => setForm(current => ({ ...current, external_reference: event.target.value }))} /><label className="label">Notes (optional)<textarea className="field min-h-20" name="notes" value={form.notes} onChange={event => setForm(current => ({ ...current, notes: event.target.value }))} /></label><Feedback error={validation || (mutation.isError ? errorMessage(mutation.error) : undefined)} /><div className="flex gap-3"><Button disabled={mutation.isPending}>{mutation.isPending ? "Saving…" : editing ? "Complete payment" : "Create payment"}</Button>{close ? <button type="button" disabled={mutation.isPending} onClick={close}>Cancel</button> : <Link to="/payments">Cancel</Link>}</div></form>;
}

export function PaymentsPage(): JSX.Element {
  const [status, setStatus] = useState(""); const [page, setPage] = useState(1);
  const payments = useQuery({ queryKey: [...paymentKey, status, page], queryFn: async () => (await api.get<PaymentPage>("/payments", { params: { status: status || undefined, page, page_size: 20 } })).data });
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Payments</h1><p className="mt-1 text-sm text-gray-500">Record and track customer payments against confirmed orders.</p></div><Can permission="payments.create"><Link to="/payments/new"><Button>Create payment</Button></Link></Can></div><Card><div className="mb-5 max-w-xs"><label className="label">Status<select className="field" value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option><option value="pending">Pending</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></label></div>{payments.isPending ? <p role="status">Loading payments…</p> : payments.isError ? <><Feedback error={errorMessage(payments.error)} /><button onClick={() => void payments.refetch()}>Retry</button></> : <><Table columns={["Reference", "Order", "Amount", "Method", "Status", "Date", "Actions"]}>{payments.data.items.map(payment => <tr key={payment.id}><td className="px-4 py-4"><Link className="font-medium text-blue-700" to={`/payments/${payment.id}`}>{payment.payment_number}</Link></td><td className="px-4 py-4 text-xs text-gray-600">{payment.order_id}</td><td className="px-4 py-4">{money(payment.amount)}</td><td className="px-4 py-4">{payment.payment_method.replace("_", " ")}</td><td className="px-4 py-4"><PaymentStatusBadge status={payment.status} /></td><td className="px-4 py-4 text-xs text-gray-500">{new Date(payment.paid_at).toLocaleDateString()}</td><td className="px-4 py-4"><Link className="text-sm font-medium text-blue-700" to={`/payments/${payment.id}`}>View</Link></td></tr>)}</Table>{payments.data.items.length === 0 && <p className="py-10 text-center text-sm text-gray-500">No payments match this status.</p>}<div className="mt-5 flex justify-between text-sm"><span>{payments.data.total} payments · Page {page}</span><div className="flex gap-3"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button disabled={page * payments.data.page_size >= payments.data.total} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</Card></div>;
}

export function PaymentEditor(): JSX.Element { return <div className="space-y-5"><div><Link className="text-sm font-medium text-blue-700" to="/payments">← Payments</Link><h1 className="mt-3 text-2xl font-semibold">Create payment</h1></div><Card><PaymentForm /></Card></div>; }

export function PaymentDetails(): JSX.Element {
  const { paymentId = "" } = useParams(); const [updating, setUpdating] = useState(false); const payment = useQuery({ queryKey: detailKey(paymentId), queryFn: async () => (await api.get<Payment>(`/payments/${paymentId}`)).data });
  if (payment.isPending) return <p role="status">Loading payment…</p>; if (payment.isError) return <Feedback error={errorMessage(payment.error)} />; const value = payment.data;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="text-sm font-medium text-blue-700" to="/payments">← Payments</Link><h1 className="mt-3 text-2xl font-semibold">{value.payment_number}</h1><p className="mt-1 text-sm text-gray-500">Payment for order {value.order_id}</p></div>{value.status === "pending" && <Can permission="payments.update"><Button onClick={() => setUpdating(true)}>Complete payment</Button></Can>}</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Card><h2 className="mb-3 font-semibold">Payment</h2><p className="text-3xl font-semibold">{money(value.amount)}</p><p className="mt-2 text-sm text-gray-500">{value.payment_method.replace("_", " ")} · <PaymentStatusBadge status={value.status} /></p></Card><Card><h2 className="mb-3 font-semibold">Order balance</h2><p className="text-sm text-gray-500">Paid amount</p><p className="text-xl font-semibold">{money(value.paid_amount)}</p><p className="mt-2 text-sm text-gray-500">Remaining: <span className="font-medium text-gray-900">{money(value.remaining_balance)}</span></p><div className="mt-3"><PaymentStateBadge state={value.payment_state} /></div></Card><Card><h2 className="mb-3 font-semibold">Payment details</h2><p className="text-sm text-gray-600">Paid: <span className="font-medium text-gray-900">{new Date(value.paid_at).toLocaleString()}</span></p><p className="mt-2 text-sm text-gray-600">Created: <span className="font-medium text-gray-900">{new Date(value.created_at).toLocaleString()}</span></p></Card></div><Card><h2 className="mb-3 font-semibold">References and notes</h2><p className="text-sm text-gray-600">External reference: <span className="font-medium text-gray-900">{value.external_reference ?? "—"}</span></p><p className="mt-3 whitespace-pre-wrap text-sm text-gray-600">{value.notes ?? "No notes recorded."}</p></Card>{updating && <Dialog title="Complete payment" close={() => setUpdating(false)}><PaymentForm payment={value} close={() => setUpdating(false)} /></Dialog>}</div>;
}
